site_name: Lost Lands Wiki
site_url: https://wiki.lostlands.org/
repo_url: https://github.com/lost-lands/wiki
repo_name: lost-lands/wiki

nav:
  - Home: index.md
  - SMP:
      - Home: smp/index.md
      - Claims: smp/claims.md

plugins:
  - search:
      lang: en

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
  icon:
    edit: material/pencil 
    view: material/eye

  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
